extends: nitro4060.yaml

audio:
  sample_rate: 250
  margin_seconds: 1.0
  n_fft: 128
  hop_length: 16
  n_mels: 64
  f_min: 0.0
  f_max: 125.0
  normalization: global
  db_min: -80.0
  db_max: 0.0

training:
  epochs: 15
  early_stopping_patience: 5

